# Generated by Django 5.2.7 on 2025-11-09 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_verification_token_user_code_expiration_and_more'),
        ('core', '0008_response_survey_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.section'),
        ),
    ]
