# Generated by Django 5.2.7 on 2025-11-16 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_section'),
        ('core', '0013_alter_surveyassignment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.section'),
        ),
    ]
