# Generated by Django 5.2.7 on 2025-11-17 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_id_alter_user_section'),
        ('accounts', '0005_alter_user_section'),
    ]

    operations = [
    ]
