# Generated by Django 5.2.7 on 2025-11-09 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_studentprofile_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='section',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='student',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
