### HAS NO ACCESS
GET http://127.0.0.1:8000/

### HAS ACCESS
GET http://127.0.0.1:8000/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYyMDAxMzE4LCJpYXQiOjE3NjE5OTc3MTgsImp0aSI6ImE0YzdjNjU0MzQ5ODQxYjc4YTFkNTgyZGZkZjg5OGY3IiwidXNlcl9pZCI6IjEiLCJ1c2VybmFtZSI6IlNhbXVlbCIsInJvbGUiOiJBRE1JTiJ9.ghha5F4CUZmh5sNJei8VBkm8ARL8-ifuQg7bFsBLmVE