### GET RESPONSE
GET http://127.0.0.1:8000/api/core/survey-response/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYyNTczNTM2LCJpYXQiOjE3NjI1Njk5MzYsImp0aSI6IjQ4ZDYwOGVlODdjOTQzMzFhZTFkMjBjNjRmMjgzY2I5IiwidXNlcl9pZCI6IjEiLCJ1c2VybmFtZSI6IlNhbXVlbCIsInJvbGUiOiJBRE1JTiJ9.O73iy-HESmfaOkCHSNnv0bXRXcedmoB_j84fzOBmy8I

### CREATE RESPONSE
POST http://127.0.0.1:8000/api/core/survey-response/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYyNTczNTM2LCJpYXQiOjE3NjI1Njk5MzYsImp0aSI6IjQ4ZDYwOGVlODdjOTQzMzFhZTFkMjBjNjRmMjgzY2I5IiwidXNlcl9pZCI6IjEiLCJ1c2VybmFtZSI6IlNhbXVlbCIsInJvbGUiOiJBRE1JTiJ9.O73iy-HESmfaOkCHSNnv0bXRXcedmoB_j84fzOBmy8I
Content-Type: application/json

{
  "response_answer": [
    {"question": 34, "answer": "My short answer"},
    {"question": 35, "answer": "Option A"}
  ]
}