### LOGIN USER
POST http://127.0.0.1:8000/api/auth/token/
Content-Type: application/json

{
    "email": "samuelalac04@gmail.com",
    "password": "Samuel@061303"
}

### GET SECTIONS
GET http://127.0.0.1:8000/api/core/sections/

### CREATE SECTION
POST http://127.0.0.1:8000/api/core/sections/
Authorization: Bearer 
Content-Type: application/json

{
    "name": "BSIT 4H-G1"
}

### UPDATE SECTION
PUT http://127.0.0.1:8000/api/core/sections/1/
Authorization: Bearer
Content-Type: application/json

{
    "name": "BSIT 4H-G1"
}

### DELETE SECTION
DELETE http://127.0.0.1:8000/api/core/sections/1/
Authorization: Bearer

### GET SECTION SURVEY
GET http://127.0.0.1:8000/api/core/section-survey/1/