### GET SURVEY ASSIGNMENTS
GET http://127.0.0.1:8000/api/core/survey-assignments/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYyNjYyOTI3LCJpYXQiOjE3NjI2NTkzMjcsImp0aSI6IjQyZTZlN2U2ZWUyMTQwNjdhODdlYTQ0M2Q2ODAzMWFlIiwidXNlcl9pZCI6IjE2IiwidXNlcm5hbWUiOiJLdWlhUmFzdSIsInJvbGUiOiJTVFVERU5UIn0.V8WYEepAL1ma1LWbfhH-d1urHy1X-6ERYqs172pt5TI

### GET SURVEY ASSIGNMENT
GET http://127.0.0.1:8000/api/core/survey-assignments/17/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYyNzA2NzE2LCJpYXQiOjE3NjI3MDMxMTYsImp0aSI6ImFjNjQ3NWQ0N2RiNjQ0N2NhNDFlMDhjNmRjMjYwMjRjIiwidXNlcl9pZCI6IjEzIiwidXNlcm5hbWUiOiJTYW11ZWxBbGFjIiwicm9sZSI6IlNUVURFTlQifQ.CBe6ePx6bClk9sP_utBVk8E_WcMtBQ2vnN3fAsZNEow


### GET SURVEY ASSIGNMENTS WITH SURVEY
GET http://127.0.0.1:8000/api/core/survey-assignment-surveys/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYyNjUyMjU5LCJpYXQiOjE3NjI2NDg2NTksImp0aSI6Ijk4ZjFiMDRlZmJjZjQ0NzM5MDllMjYwMTg4NzE5NWVlIiwidXNlcl9pZCI6IjEiLCJ1c2VybmFtZSI6IlNhbXVlbCIsInJvbGUiOiJBRE1JTiJ9.WcnHLr4XBMqquOt-COEguP5qu3GOKfz5S_b5jVxxqxQ 

### CREATE SURVEY ASSIGNMENTS WITH SURVEY
POST http://127.0.0.1:8000/api/core/survey-assignment-surveys/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYyNjIxNzk1LCJpYXQiOjE3NjI2MTgxOTUsImp0aSI6ImUwNTdkNjY4ZWE4NDQzOGJiNmE5NjM1ZDNiZTY5NDcwIiwidXNlcl9pZCI6IjEiLCJ1c2VybmFtZSI6IlNhbXVlbCIsInJvbGUiOiJBRE1JTiJ9.-A3AZ3YsveuBDX2ZAN59drGnwC3GQkiNT7aaJaxLXiI
Content-Type: application/json

{
    "survey": 16,
    "sections": [1,2]
}

### GET SURVEY ASSIGNMENT WITH SURVEY
GET http://127.0.0.1:8000/api/core/survey-assignment-surveys/17/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYyNzA2NzE2LCJpYXQiOjE3NjI3MDMxMTYsImp0aSI6ImFjNjQ3NWQ0N2RiNjQ0N2NhNDFlMDhjNmRjMjYwMjRjIiwidXNlcl9pZCI6IjEzIiwidXNlcm5hbWUiOiJTYW11ZWxBbGFjIiwicm9sZSI6IlNUVURFTlQifQ.CBe6ePx6bClk9sP_utBVk8E_WcMtBQ2vnN3fAsZNEow
### UPDATE SURVEY_ASSIGNMENTS WITH SURVEY
PUT http://127.0.0.1:8000/api/core/survey-assignment-surveys/13/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYyNjEzNjQxLCJpYXQiOjE3NjI2MTAwNDEsImp0aSI6ImFlNWJiY2E3ZjQ5NTQ0OGNhYzI3MWVjNDIxMjA2Yjg0IiwidXNlcl9pZCI6IjEiLCJ1c2VybmFtZSI6IlNhbXVlbCIsInJvbGUiOiJBRE1JTiJ9.23e6F3ibhJ4ZE86koN294pjOybLCYb_dhCa-59ZKKoI
Content-Type: application/json

{
    "survey": 13,
    "sections": [2]
}