### GET SURVEY ASSIGNMENTS
GET http://127.0.0.1:8000/api/core/survey-assignments/?search=last
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYzMzg4OTQwLCJpYXQiOjE3NjMzODUzNDAsImp0aSI6ImYzODNmYmUwYmU2YTQ2YjU5NDQ1OTNmNmE4ZTFjMGE4IiwidXNlcl9pZCI6IjEiLCJ1c2VybmFtZSI6IlNhbXVlbCIsInJvbGUiOiJBRE1JTiJ9.VKtSQpEnMiUMIGSI8Zs8wbQ0iwIRvDqroGD7RmBmm3k

### GET SURVEY ASSIGNMENT
GET http://127.0.0.1:8000/api/core/survey-assignments/17/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYzMTk1NDA1LCJpYXQiOjE3NjMxOTE4MDUsImp0aSI6IjExODllMmE5YTc0ZDRiZmY5MzBjYjc2MjRmZjY4NWVmIiwidXNlcl9pZCI6IjEiLCJ1c2VybmFtZSI6IlNhbXVlbCIsInJvbGUiOiJBRE1JTiJ9.zwEKvhHRbY3bR8oLZuhvofDyIr1kl1E9qGtr1HzEHQM

### GET SURVEY ASSIGNMENTS WITH SURVEY
GET http://127.0.0.1:8000/api/core/survey-assignment-surveys/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYyNjUyMjU5LCJpYXQiOjE3NjI2NDg2NTksImp0aSI6Ijk4ZjFiMDRlZmJjZjQ0NzM5MDllMjYwMTg4NzE5NWVlIiwidXNlcl9pZCI6IjEiLCJ1c2VybmFtZSI6IlNhbXVlbCIsInJvbGUiOiJBRE1JTiJ9.WcnHLr4XBMqquOt-COEguP5qu3GOKfz5S_b5jVxxqxQ 

### CREATE SURVEY ASSIGNMENTS WITH SURVEY
POST http://127.0.0.1:8000/api/core/survey-assignment-surveys/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYyODMwMzI5LCJpYXQiOjE3NjI4MjY3MjksImp0aSI6ImU1Y2U3MDUyYWViOTQ5M2JiNjk4NDAwYzFjNjNhYTdkIiwidXNlcl9pZCI6IjEiLCJ1c2VybmFtZSI6IlNhbXVlbCIsInJvbGUiOiJBRE1JTiJ9.XSPEWl0D4-AR_TifmtS_-519dAmLjpIpqN_r7K3S6JU
Content-Type: application/json

{
    "survey": 17,
    "sections": [1]
}

### GET SURVEY ASSIGNMENT WITH SURVEY
GET http://127.0.0.1:8000/api/core/survey-assignment-surveys/30/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYzMTk1NDA1LCJpYXQiOjE3NjMxOTE4MDUsImp0aSI6IjExODllMmE5YTc0ZDRiZmY5MzBjYjc2MjRmZjY4NWVmIiwidXNlcl9pZCI6IjEiLCJ1c2VybmFtZSI6IlNhbXVlbCIsInJvbGUiOiJBRE1JTiJ9.zwEKvhHRbY3bR8oLZuhvofDyIr1kl1E9qGtr1HzEHQM

### UPDATE SURVEY_ASSIGNMENTS WITH SURVEY
PUT http://127.0.0.1:8000/api/core/survey-assignment-surveys/18/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYyNzgyNDQ5LCJpYXQiOjE3NjI3Nzg4NDksImp0aSI6IjVhOThiNzVlYjRlYjRlNDNhNzEyNzE1NjZmZjhkN2QxIiwidXNlcl9pZCI6IjEiLCJ1c2VybmFtZSI6IlNhbXVlbCIsInJvbGUiOiJBRE1JTiJ9.CPAH15HGh0gbhWdj86gmRy0MXN5x-eXJyG9Pt-TbAi0
Content-Type: application/json

{
    "survey": 17,
    "sections": [2]
}

### GET SURVEY ASSIGNMENT WITH RESPONSES
GET http://127.0.0.1:8000/api/core/survey-assignment-responses/30/


### GET SURVEY ASSIGNMENT WITH QUESTION AND RESPONSES
GET http://127.0.0.1:8000/api/core/survey-assignment-qa/30/