# Generated by Django 5.2.7 on 2025-11-06 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_question_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyassignment',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_surveys', to='core.survey'),
        ),
    ]
