# Generated by Django 5.2.7 on 2025-11-08 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_response_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='survey_assignment',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='survey_assignment', to='core.surveyassignment'),
            preserve_default=False,
        ),
    ]
