# Generated by Django 5.2.7 on 2025-11-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_response_survey_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyassignment',
            name='completed',
        ),
        migrations.AddField(
            model_name='surveyassignment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=20),
        ),
    ]
