# Generated by Django 5.2.7 on 2025-11-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_surveyassignment_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyassignment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
    ]
