# Generated by Django 5.2.7 on 2025-11-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_surveyassignment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyassignment',
            name='editable',
            field=models.BooleanField(default=False),
        ),
    ]
