# Generated by Django 5.2.7 on 2025-11-16 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_surveyassignment_editable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='survey_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_assignment_response', to='core.surveyassignment'),
        ),
    ]
