# Generated by Django 5.2.7 on 2025-11-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_response_survey_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyassignment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('past_due', 'Past_Due')], default='active', max_length=20),
        ),
    ]
