# Generated by Django 5.2.7 on 2025-11-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_surveyassignment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyassignment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('past due', 'Past_Due')], default='active', max_length=20),
        ),
    ]
